patterns:
  group_size:
    label: Velikost skupiny
    dist:
      type: lognormvariate
      mean:
        min_value: 1
        max_value: 8
        step: 1
      std:
        min_value: 0.1
        max_value: 1.0
        step: 0.1
  wants_table:
    label: Požadavek na stůl
    dist:
      type: bernoulli
      p:
        min_value: 0.05
        max_value: 1
        step: 0.05
  queue_patience:
    label: Trpělivost
    quantity: time
    dist:
      type: lognormvariate
      mean:
        min_value: 0
        max_value: 20
        step: 0.0166
      std:
        min_value: 0
        max_value: 5.0
        step: 0.0166
  consumption_speed_modifier:
    label: Koeficient tempa konzumace
    dist:
      type: lognormvariate
      mean:
        min_value: 0.4
        max_value: 5.0
        step: 0.05
      std:
        min_value: 0.0
        max_value: 0.5
        step: 0.05
  time_range:
    label: Čas
    quantity: time
    min_value: 420
    max_value: 1320
    step: 1
  arrival_rate:
    label: Příchody/hod
    min_value: 1
    max_value: 100
    step: 1
  customer_mix:
    label: Váhy typů zákazníků
    min_value: 0
    max_value: 10
    step: 1
  cashiers:
    label: Počet pokladen
    min_value: 1
    max_value: 3
    step: 1
  baristas:
    label: Počet baristů
    min_value: 1
    max_value: 5
    step: 1
  capacity_counts:
    label: Směny
    item_prefix: Směna
  capacity_count:
    label: Počet
    min_value: 1
    max_value: 4
    step: 1
  capacity:
    label: Kapacita
    quantity: time
    min_value: 1
    max_value: 4
    step: 1
  tables_count:
    label: Počet
    min_value: 0
    max_value: 10
    step: 1
  table_capacity:
    label: Kapacita
    min_value: 1
    max_value: 20
    step: 1
  consumption_time:
    label: Čas konzumace
    quantity: time
    dist:
      type: lognormvariate
      mean:
        min_value: 5.0
        max_value: 20.0
        step: 0.1
      std:
        min_value: 0.0
        max_value: 6.0
        step: 0.1
  order_process_time:
    label: Čas přijetí objednávky
    quantity: time
    dist:
      type: lognormvariate
      mean:
        min_value: 0.2
        max_value: 1.6
        step: 0.1
      std:
        min_value: 0.2
        max_value: 1.6
        step: 0.1
  recipe_time:
    label: Čas výkonu
    quantity: time
    dist:
      type: lognormvariate
      mean:
        min_value: 0.2
        max_value: 1.6
        step: 0.1
      std:
        min_value: 0.2
        max_value: 1.6
        step: 0.1
  items_weights:
    label: Váhy typů položek
    min_value: 0
    max_value: 10
    step: 1
  order_categories_preferences:
    label: Váhy kategorií položek
    min_value: 0
    max_value: 10
    step: 1
  recipe:
    label: Postup
  task_used_resources:
    label: Váhy kategorií položek
    section: used_resources
customer_types:
  label: Typy zákazníků
  1:
    label: Ranní spěchající do práce
    group_size:
      dist:
        type: lognormvariate
        mean:
          value: 1
        std:
          value: 0.2
    wants_table:
      dist:
        type: bernoulli
        p:
          value: 0.05
    queue_patience:
      dist:
        type: lognormvariate
        mean:
          value: 2.0086
        std:
          value: 0.3984
    consumption_speed_modifier:
      dist:
        type: lognormvariate
        mean:
          value: 0.75
        std:
          value: 0.1
    order_categories_preferences:
      section: item_categories
      weights:
        1: 10.0
        2: 4.0
  2:
    label: Dopolední maminka
    group_size:
      dist:
        type: lognormvariate
        mean:
          value: 2
        std:
          value: 0.4
    wants_table:
      dist:
        type: bernoulli
        p:
          value: 0.9
    queue_patience:
      dist:
        type: lognormvariate
        mean:
          value: 5.0464
        std:
          value: 0.9628
    consumption_speed_modifier:
      dist:
        type: lognormvariate
        mean:
          value: 5.0
        std:
          value: 0.4
    order_categories_preferences:
      section: item_categories
      weights:
        1: 10.0
        2: 6.0
        3: 3.0
  3:
    label: Důchodce
    group_size:
      dist:
        type: lognormvariate
        mean:
          value: 2
        std:
          value: 0.4
    wants_table:
      dist:
        type: bernoulli
        p:
          value: 0.9
    queue_patience:
      dist:
        type: lognormvariate
        mean:
          value: 5.0464
        std:
          value: 2.0252
    consumption_speed_modifier:
      dist:
        type: lognormvariate
        mean:
          value: 5.0
        std:
          value: 0.4
    order_categories_preferences:
      section: item_categories
      weights:
        1: 9.0
        2: 6.0
        3: 1.0
  4:
    label: Zaměstnanec po obědě
    group_size:
      dist:
        type: lognormvariate
        mean:
          value: 2
        std:
          value: 0.6
    wants_table:
      dist:
        type: bernoulli
        p:
          value: 0.9
    queue_patience:
      dist:
        type: lognormvariate
        mean:
          value: 3.0212
        std:
          value: 1.992
    consumption_speed_modifier:
      dist:
        type: lognormvariate
        mean:
          value: 1.0
        std:
          value: 0.4
    order_categories_preferences:
      section: item_categories
      weights:
        1: 10.0
        2: 1.0
  5:
    label: Nakupující
    group_size:
      dist:
        type: lognormvariate
        mean:
          value: 2
        std:
          value: 0.6
    wants_table:
      dist:
        type: bernoulli
        p:
          value: 0.7000000000000001
    queue_patience:
      dist:
        type: lognormvariate
        mean:
          value: 3.0378
        std:
          value: 1.0126
    consumption_speed_modifier:
      dist:
        type: lognormvariate
        mean:
          value: 1.0
        std:
          value: 0.5
    order_categories_preferences:
      section: item_categories
      weights:
        1: 8.0
        2: 6.0
        3: 3.0
time_intervals:
  label: Časové intervaly
  1:
    label: Ranní špička
    time_range:
      range:
      - 420
      - 600
    arrival_rate:
      value: 60
    customer_mix:
      section: customer_types
      weights:
        1: 9
        2: 2
  2:
    label: Dopoledne
    time_range:
      range:
      - 600
      - 720
    arrival_rate:
      value: 30
    customer_mix:
      section: customer_types
      weights:
        1: 1.0
        2: 8.0
        3: 8.0
        4: 2.0
        5: 5.0
  3:
    label: Polední nápor
    time_range:
      range:
      - 720
      - 840
    arrival_rate:
      value: 50
    customer_mix:
      section: customer_types
      weights:
        1: 1.0
        2: 3.0
        3: 5.0
        4: 10.0
        5: 7.0
  4:
    label: Odpoledne
    time_range:
      range:
      - 840
      - 1080
    arrival_rate:
      value: 40
    customer_mix:
      section: customer_types
      weights:
        1: 1.0
        2: 5.0
        3: 7.0
        4: 4.0
        5: 8.0
  5:
    label: Večerní klid
    time_range:
      range:
      - 1080
      - 1260
    arrival_rate:
      value: 20
    customer_mix:
      section: customer_types
      weights:
        2: 1.0
        3: 3.0
        4: 1.0
        5: 5.0
used_resources:
  label: Zdroje
  1:
    label: Kávovar
    capacity:
      value: 1
    capacity_counts:
      1:
        time_range:
          range:
          - 420
          - 1260
        capacity_count:
          value: 2
  2:
    label: Trouba
    capacity:
      value: 1
    capacity_counts:
      1:
        time_range:
          range:
          - 420
          - 1260
        capacity_count:
          value: 2
  3:
    label: Pokladní
    capacity:
      value: 1
    capacity_counts:
      1:
        time_range:
          range:
          - 420
          - 781
        capacity_count:
          value: 1.0
      2:
        time_range:
          range:
          - 781
          - 1260
        capacity_count:
          value: 1.0
  4:
    label: Barista
    capacity:
      value: 1
    capacity_counts:
      1:
        time_range:
          range:
          - 420
          - 781
        capacity_count:
          value: 1.0
      2:
        time_range:
          range:
          - 781
          - 1260
        capacity_count:
          value: 2.0
tables:
  label: Kapacita k sezení
  1:
    label: Stul typ 1
    table_capacity:
      value: 4
    tables_count:
      value: 5.0
  2:
    label: Stul typ 2
    table_capacity:
      value: 6
    tables_count:
      value: 6.0
item_categories:
  label: Kategorie položek menu
  1:
    label: Nápoj
    items_weights:
      section: menu_items
      weights:
        1: 10.0
        2: 7.0
    consumption_time:
      dist:
        type: lognormvariate
        mean:
          value: 12.0
        std:
          value: 2
  2:
    label: Jídlo malé
    items_weights:
      section: menu_items
      weights:
        3: 10.0
    consumption_time:
      dist:
        type: lognormvariate
        mean:
          value: 10.0
        std:
          value: 6.0
  3:
    label: Jídlo velké
    items_weights:
      section: menu_items
      weights:
        4: 10.0
    consumption_time:
      dist:
        type: lognormvariate
        mean:
          value: 15.0
        std:
          value: 6.0
menu_items:
  label: Položky menu
  1:
    label: Espresso
    recipe:
      1:
        label: Mletí a příprava
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
        task_used_resources:
          resources:
            4: 1
      2:
        label: Extrakce
        task_used_resources:
          resources:
            1: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
      3:
        label: Výdej
        task_used_resources:
          resources:
            1: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
  2:
    label: Cappuccino
    recipe:
      1:
        label: Mletí a příprava
        task_used_resources:
          resources:
            4: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
      2:
        label: Extrakce
        task_used_resources:
          resources:
            1: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
      3:
        label: Šlehání mléka a dokončení
        task_used_resources:
          resources:
            4: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
      4:
        label: Výdej
        task_used_resources:
          resources:
            4: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
  3:
    label: Teplý croissant
    recipe:
      1:
        label: Vybalení
        task_used_resources:
          resources:
            4: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
      2:
        label: Rozpékání
        task_used_resources:
          resources:
            2: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
      3:
        label: Výdej
        task_used_resources:
          resources:
            4: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
  4:
    label: Velký Sandwich
    recipe:
      1:
        label: Vybalení a příprava
        task_used_resources:
          resources:
            4: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
      2:
        label: Rozpékání
        task_used_resources:
          resources:
            2: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 1.6
            std:
              value: 1.6
      3:
        label: Výdej
        task_used_resources:
          resources:
            4: 1
        recipe_time:
          dist:
            type: lognormvariate
            mean:
              value: 0.6000000000000001
            std:
              value: 0.6000000000000001
order_process:
  label: Proces objednávky
  task_used_resources:
    resources:
      3: 1
  order_process_time:
    dist:
      type: lognormvariate
      mean:
        value: 0.2
      std:
        value: 0.6000000000000001
